### ISSUE TITLE
How to use for Forms in django itself

### ISSUE THREAD

**Issue by andrew-lee-metaswitch** [tyomo4ka/django-reactive#7]
* django-reactive version: django-reactive==0.0.4
* Django version: Django==2.1.15
* Python version: 3.6.8
* Operating System: Linux

### Description

Cool Project!

I'm having problems using this to create ModelForms to use in django itself (i.e. not the Admin UI).

I have a forms.ModelForm object based of the Model class with this ReactJSONSchemaField field, I then try and render it in a HTML template with the `{{ form }}`  as per https://docs.djangoproject.com/en/3.0/ref/forms/api/#outputting-forms-as-html but the resultant page is blank. Is this WAD? I suspect this is a fundamental limitation to do with how this appworks and how django tries to take form objects and render them.

**Comment by tyomo4ka** [comment]
Hi @andrew-lee-metaswitch. 

Thanks, for raising the issue. To be honest, we only use it in admin as described in README.

I've never had an intention to use it from the model forms. I will check if it's possible if I have time next week.

**Comment by erm** [comment]
I tested this using a normal `FormView` and was able to get it to render correctly, you'll need to include the following:

- A call to the [form media property](https://docs.djangoproject.com/en/3.0/topics/forms/media/#media-on-forms) using `{{ form.media }}`

- An input tag with `name="save"` because the `django_reactive.js` disables this element on load. I assume this is because Django admin templates use this name.

Working example:

`views.py`

```python
from django.views.generic.edit import FormView
from django.forms import ModelForm

from testapp.models import TestModel


class TestModelForm(ModelForm):
    class Meta:
        model = TestModel
        fields = ["simple"]


class TestView(FormView):
    template_name = "test.html"
    form_class = TestModelForm
    model = TestModel
    success_url = "/test/"

    def form_valid(self, form):
        form.save()

        return super().form_valid(form)
```

`templates/test.html`

```html
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
</head>
<body>
  {{ form.media }}
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save" class="default" name="_save">
  </form>
</body>
</html>
```

I think this could be a starting point to make its usage more generic, though the solution could just be to document this behaviour for how to use outside Django admin.

**Comment by andrew-lee-metaswitch** [comment]
Thanks both!
I wasn't aware of the  `form.media` method.

Yes, I think documenting this in the README would be a sufficient fix.

For the record, it's mildly interesting that `django_reactive.js` disables save: we've been playing around with using Django as a front-end to YAML files (defined by a JSON schema) which are stored in git, so using the "Save button" to send a pot to git to save the files under version-control (bypassing all the Postgres stuff in django).

**Comment by tyomo4ka** [comment]
@jordaneremieff 

Thanks a lot for your PR first of all. It's all great changes. And thanks for sharing the way of using it in regular Django forms.

**Comment by tyomo4ka** [comment]
@andrew-lee-metaswitch 

@andrew-lee-metaswitch 

I think you need DB anyways to run Django. I don't know all the requirements obviously. 
But the way how I imagine it working is by having a `post_save` signal or async Celery task which saves the files to Git after Postgres. I used a similar approach in one of the projects (it was Symfony based, not Django). 

So the workflow was -> data hits API -> API runs validations against JSON schema and stores data in DB -> async task pull data from DB and generates files -> there are a set of tools run over the generated files (something like pre-commit hooks)  -> commit to Git.

I only used git in order to be able to restore some specific point in time. And the DB data was used by the app to do all the app logic.

**Comment by tyomo4ka** [comment]
Thanks to @jordaneremieff README was updated with more examples that are demonstrated the requested behaviour.
